name: Automacao BDR Start RH

on:
  schedule:
    # Roda toda quinta-feira às 12:00 UTC (09:00 no Horário de Brasília)
    - cron: '0 12 * * 4'
  workflow_dispatch:

jobs:
  executar-script:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar codigo do repositorio
        uses: actions/checkout@v4

      - name: Configurar ambiente Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar bibliotecas requeridas
        run: pip install requests

      - name: Executar Automacao
        env:
          HUBSPOT_ACCESS_TOKEN: ${{ secrets.HUBSPOT_ACCESS_TOKEN }}
          APOLLO_API_KEY: ${{ secrets.APOLLO_API_KEY }}
          JOEL_EMAIL_PASSWORD: ${{ secrets.JOEL_EMAIL_PASSWORD }}
      
        run: python buscar_empresas_aleatorias_github.py
